# Generated by Django 5.2.11 on 2026-02-03 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name="Rekawice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nazwa", models.CharField(max_length=120, verbose_name="Nazwa")),
                ("marka", models.CharField(max_length=80, verbose_name="Marka")),
                ("waga_oz", models.PositiveIntegerField(verbose_name="Waga (oz)")),
                ("material", models.CharField(max_length=80, verbose_name="Materiał")),
                ("zapiecie", models.CharField(choices=[("rzep", "Rzep"), ("sznurowane", "Sznurowane")], default="rzep", max_length=12, verbose_name="Zapięcie")),
                ("poziom", models.CharField(choices=[("poczatkujacy", "Początkujący"), ("sredniozaawansowany", "Średniozaawansowany"), ("zaawansowany", "Zaawansowany")], max_length=20, verbose_name="Poziom")),
                ("cena", models.DecimalField(decimal_places=2, max_digits=8, verbose_name="Cena (PLN)")),
                ("opis", models.TextField(blank=True, verbose_name="Opis")),
                ("utworzono", models.DateTimeField(auto_now_add=True, verbose_name="Dodano")),
            ],
            options={
                "verbose_name": "Rękawice bokserskie",
                "verbose_name_plural": "Rękawice bokserskie",
                "ordering": ["nazwa"],
            },
        ),
        migrations.CreateModel(
            name="Buty",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nazwa", models.CharField(max_length=120, verbose_name="Nazwa")),
                ("marka", models.CharField(max_length=80, verbose_name="Marka")),
                ("rozmiar_eu", models.DecimalField(decimal_places=1, max_digits=4, verbose_name="Rozmiar EU")),
                ("wsparcie_kostki", models.BooleanField(default=True, verbose_name="Wsparcie kostki")),
                ("material", models.CharField(max_length=80, verbose_name="Materiał")),
                ("poziom", models.CharField(choices=[("poczatkujacy", "Początkujący"), ("sredniozaawansowany", "Średniozaawansowany"), ("zaawansowany", "Zaawansowany")], max_length=20, verbose_name="Poziom")),
                ("cena", models.DecimalField(decimal_places=2, max_digits=8, verbose_name="Cena (PLN)")),
                ("opis", models.TextField(blank=True, verbose_name="Opis")),
                ("utworzono", models.DateTimeField(auto_now_add=True, verbose_name="Dodano")),
            ],
            options={
                "verbose_name": "Buty do boksu",
                "verbose_name_plural": "Buty do boksu",
                "ordering": ["nazwa"],
            },
        ),
        migrations.CreateModel(
            name="Owijki",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nazwa", models.CharField(max_length=120, verbose_name="Nazwa")),
                ("marka", models.CharField(max_length=80, verbose_name="Marka")),
                ("dlugosc_cm", models.PositiveIntegerField(verbose_name="Długość (cm)")),
                ("elastyczne", models.BooleanField(default=True, verbose_name="Elastyczne")),
                ("material", models.CharField(max_length=80, verbose_name="Materiał")),
                ("cena", models.DecimalField(decimal_places=2, max_digits=8, verbose_name="Cena (PLN)")),
                ("opis", models.TextField(blank=True, verbose_name="Opis")),
                ("utworzono", models.DateTimeField(auto_now_add=True, verbose_name="Dodano")),
            ],
            options={
                "verbose_name": "Owijki",
                "verbose_name_plural": "Owijki",
                "ordering": ["nazwa"],
            },
        ),
        migrations.CreateModel(
            name="Ochraniacze",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nazwa", models.CharField(max_length=120, verbose_name="Nazwa")),
                ("marka", models.CharField(max_length=80, verbose_name="Marka")),
                ("dopasowanie", models.CharField(choices=[("boil_bite", "Boil & Bite"), ("custom", "Custom"), ("pasek", "Z paskiem")], max_length=20, verbose_name="Dopasowanie")),
                ("rozmiar", models.CharField(choices=[("S", "S"), ("M", "M"), ("L", "L"), ("XL", "XL")], max_length=4, verbose_name="Rozmiar")),
                ("cena", models.DecimalField(decimal_places=2, max_digits=8, verbose_name="Cena (PLN)")),
                ("opis", models.TextField(blank=True, verbose_name="Opis")),
                ("utworzono", models.DateTimeField(auto_now_add=True, verbose_name="Dodano")),
            ],
            options={
                "verbose_name": "Ochraniacz na zęby",
                "verbose_name_plural": "Ochraniacze na zęby",
                "ordering": ["nazwa"],
            },
        ),
        migrations.CreateModel(
            name="Zestawy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nazwa", models.CharField(max_length=120, verbose_name="Nazwa zestawu")),
                ("poziom", models.CharField(choices=[("poczatkujacy", "Początkujący"), ("sredniozaawansowany", "Średniozaawansowany"), ("zaawansowany", "Zaawansowany")], max_length=20, verbose_name="Poziom")),
                ("cena_zestawu", models.DecimalField(decimal_places=2, max_digits=8, verbose_name="Cena zestawu (PLN)")),
                ("uwagi", models.TextField(blank=True, verbose_name="Uwagi")),
                ("utworzono", models.DateTimeField(auto_now_add=True, verbose_name="Dodano")),
                ("buty", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="sparring_sets", to="sprzet.buty", verbose_name="Buty")),
                ("ochraniacz", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="sparring_sets", to="sprzet.ochraniacze", verbose_name="Ochraniacz na zęby")),
                ("owijki", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="sparring_sets", to="sprzet.owijki", verbose_name="Owijki")),
                ("rekawice", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="sparring_sets", to="sprzet.rekawice", verbose_name="Rękawice")),
            ],
            options={
                "verbose_name": "Sparring set",
                "verbose_name_plural": "Sparring sety",
                "ordering": ["-utworzono"],
            },
        ),
    ]
